NIFTY_50 = {
    "Zomato": "ZOMATO.NS",
    "Paytm (One97 Communications)": "PAYTM.NS",
    "Nykaa (FSN E-Commerce)": "NYKAA.NS",
    "Reliance Industries": "RELIANCE.NS",
    "Tata Consultancy Services (TCS)": "TCS.NS",
    "HDFC Bank": "HDFCBANK.NS",
    "ICICI Bank": "ICICIBANK.NS",
    "Bharti Airtel": "BHARTIARTL.NS",
    "State Bank of India (SBI)": "SBIN.NS",
    "Infosys": "INFY.NS",
    "ITC": "ITC.NS",
    "Hindustan Unilever (HUL)": "HINDUNILVR.NS",
    "Larsen & Toubro (L&T)": "LT.NS",
    "Bajaj Finance": "BAJFINANCE.NS",
    "HCL Technologies": "HCLTECH.NS",
    "Maruti Suzuki": "MARUTI.NS",
    "Sun Pharma": "SUNPHARMA.NS",
    "Kotak Mahindra Bank": "KOTAKBANK.NS",
    "Tata Motors": "TATAMOTORS.NS",
    "NTPC": "NTPC.NS",
    "Axis Bank": "AXISBANK.NS",
    "Titan Company": "TITAN.NS",
    "ONGC": "ONGC.NS",
    "UltraTech Cement": "ULTRACEMCO.NS",
    "Asian Paints": "ASIANPAINT.NS",
    "Coal India": "COALINDIA.NS",
    "Tata Steel": "TATASTEEL.NS",
    "Power Grid Corp": "POWERGRID.NS",
    "Bajaj Finserv": "BAJAJFINSV.NS",
    "Nestle India": "NESTLEIND.NS",
    "Mahindra & Mahindra (M&M)": "M&M.NS",
    "Wipro": "WIPRO.NS",
    "JSW Steel": "JSWSTEEL.NS",
    "Grasim Industries": "GRASIM.NS",
    "Hindalco": "HINDALCO.NS",
    "Tech Mahindra": "TECHM.NS",
    "HDFC Life": "HDFCLIFE.NS",
    "Bajaj Auto": "BAJAJ-AUTO.NS",
    "Tata Consumer Products": "TATACONSUM.NS",
    "IndusInd Bank": "INDUSINDBK.NS",
    "Apollo Hospitals": "APOLLOHOSP.NS",
    "Cipla": "CIPLA.NS",
    "Dr. Reddy's Laboratories": "DRREDDY.NS",
    "Hero MotoCorp": "HEROMOTOCO.NS",
    "Eicher Motors": "EICHERMOT.NS",
    "Divi's Laboratories": "DIVISLAB.NS",
    "BPCL": "BPCL.NS",
    "UPL": "UPL.NS",
    "Britannia Industries": "BRITANNIA.NS",
    "LTIMindtree": "LTIM.NS",
    "SBI Life Insurance": "SBILIFE.NS",
    "Adani Enterprises": "ADANIENT.NS",
    "Adani Ports": "ADANIPORTS.NS",
    "🔍 Custom/Other (Type Below)": "CUSTOM"
}
