ALL_STOCKS = {
    # NIFTY 50 & Mainboard
    "Zomato Limited": "ZOMATO.NS",
    "Paytm (One97 Communications)": "PAYTM.NS",
    "Nykaa (FSN E-Commerce)": "NYKAA.NS",
    "Reliance Industries": "RELIANCE.NS",
    "Tata Consultancy Services (TCS)": "TCS.NS",
    "HDFC Bank": "HDFCBANK.NS",
    "ICICI Bank": "ICICIBANK.NS",
    "Bharti Airtel": "BHARTIARTL.NS",
    "State Bank of India (SBI)": "SBIN.NS",
    "Infosys": "INFY.NS",
    "ITC": "ITC.NS",
    "Hindustan Unilever (HUL)": "HINDUNILVR.NS",
    "Larsen & Toubro (L&T)": "LT.NS",
    "Bajaj Finance": "BAJFINANCE.NS",
    "HCL Technologies": "HCLTECH.NS",
    "Maruti Suzuki": "MARUTI.NS",
    "Sun Pharma": "SUNPHARMA.NS",
    "Kotak Mahindra Bank": "KOTAKBANK.NS",
    "Tata Motors": "TATAMOTORS.NS",
    "NTPC": "NTPC.NS",
    "Axis Bank": "AXISBANK.NS",
    "Titan Company": "TITAN.NS",
    "ONGC": "ONGC.NS",
    "UltraTech Cement": "ULTRACEMCO.NS",
    "Asian Paints": "ASIANPAINT.NS",
    "Coal India": "COALINDIA.NS",
    "Tata Steel": "TATASTEEL.NS",
    "Power Grid Corp": "POWERGRID.NS",
    "Bajaj Finserv": "BAJAJFINSV.NS",
    "Nestle India": "NESTLEIND.NS",
    "Mahindra & Mahindra (M&M)": "M&M.NS",
    "Wipro": "WIPRO.NS",
    "JSW Steel": "JSWSTEEL.NS",
    "Grasim Industries": "GRASIM.NS",
    "Hindalco": "HINDALCO.NS",
    "Tech Mahindra": "TECHM.NS",
    "HDFC Life": "HDFCLIFE.NS",
    "Bajaj Auto": "BAJAJ-AUTO.NS",
    "Tata Consumer Products": "TATACONSUM.NS",
    "IndusInd Bank": "INDUSINDBK.NS",
    "Apollo Hospitals": "APOLLOHOSP.NS",
    "Cipla": "CIPLA.NS",
    "Dr. Reddy's Laboratories": "DRREDDY.NS",
    "Hero MotoCorp": "HEROMOTOCO.NS",
    "Eicher Motors": "EICHERMOT.NS",
    "Divi's Laboratories": "DIVISLAB.NS",
    "BPCL": "BPCL.NS",
    "UPL": "UPL.NS",
    "Britannia Industries": "BRITANNIA.NS",
    "LTIMindtree": "LTIM.NS",
    "SBI Life Insurance": "SBILIFE.NS",
    "Adani Enterprises": "ADANIENT.NS",
    "Adani Ports": "ADANIPORTS.NS",
    
    # NSE SME (Emerge) Stocks
    "E2E Networks Ltd (SME)": "E2E.NS",
    "Phantom Digital Effects Ltd (SME)": "PHANTOMFX.NS",
    "Droneacharya Aerial Innovations Ltd (SME)": "DRONE.NS",
    "Alpex Solar Ltd (SME)": "ALPEXSOLAR.NS",
    "Insolation Energy Ltd (SME)": "INA.NS",
    "Spectrum Talent Management Ltd (SME)": "SPECTRUM.NS",
    "Basilic Fly Studio Ltd (SME)": "BASILIC.NS",
    "RBM Infracon Ltd (SME)": "RBMINFRA.NS",
    "Remus Pharmaceuticals Ltd (SME)": "REMUS.NS",
    "Krishca Strapping Solutions Ltd (SME)": "KRISHCA.NS",
    "Techknowgreen Solutions Ltd (SME)": "TECHKNOW.NS",
    "Kody Technolab Ltd (SME)": "KODYTECH.NS",
    "Srivari Spices and Foods Ltd (SME)": "SRIVARI.NS",
    "Ahasolar Technologies Ltd (SME)": "AHASOLAR.NS",
    "Vinsys IT Services India Ltd (SME)": "VINSYS.NS",
    "Yasons Chemex Care Ltd (SME)": "YASONS.NS",
    "Cellecor Gadgets Ltd (SME)": "CELLECOR.NS",
    "Kahan Packaging Ltd (SME)": "KAHAN.NS",
    "Pramara Promotions Ltd (SME)": "PRAMARA.NS",
    "Meson Valves India Ltd (SME)": "MESON.NS",

    "🔍 Custom/Other (Type Below)": "CUSTOM"
}
