ALL_STOCKS = {
    "3M India Ltd": "3MINDIA.NS",
    "ABB India Ltd": "ABB.NS",
    "ACC Ltd": "ACC.NS",
    "AIA Engineering Ltd": "AIAENG.NS",
    "Adani Enterprises Ltd": "ADANIENT.BO",
    "Adani Green Energy Ltd": "ADANIGREEN.NS",
    "Adani Ports and Special Economic Zone Ltd": "ADANIPORTS.BO",
    "Adani Power Ltd": "ADANIPOWER.NS",
    "Adani Total Gas Ltd": "ATGL.NS",
    "Adani Transmission Ltd": "ADANITRANS.NS",
    "Ajanta Pharma Ltd": "AJANTPHARM.NS",
    "Alkem Laboratories Ltd": "ALKEM.NS",
    "Ambuja Cements Ltd": "AMBUJACEM.NS",
    "Apollo Hospitals Enterprise Ltd": "APOLLOHOSP.BO",
    "Apollo Tyres Ltd": "APOLLOTYRE.NS",
    "Ashok Leyland Ltd": "ASHOKLEY.NS",
    "Asian Paints Ltd": "ASIANPAINT.BO",
    "Astral Ltd": "ASTRAL.NS",
    "Aurobindo Pharma Ltd": "AUROPHARMA.NS",
    "Axis Bank Ltd": "AXISBANK.BO",
    "BEL Ltd": "BEL.NS",
    "BEML Ltd": "BEML.NS",
    "BPCL Ltd": "BPCL.BO",
    "Bajaj Auto Ltd": "BAJAJ-AUTO.BO",
    "Bajaj Finance Ltd": "BAJFINANCE.BO",
    "Bajaj Finserv Ltd": "BAJAJFINSV.BO",
    "Bajaj Holdings & Investment Ltd": "BAJAJHLDNG.BO",
    "Balkrishna Industries Ltd": "BALKRISIND.NS",
    "Bandhan Bank Ltd": "BANDHANBNK.NS",
    "Bank of Baroda": "BANKBARODA.NS",
    "Bata India Ltd": "BATAINDIA.NS",
    "Bayer Cropscience Ltd": "BAYERCROP.NS",
    "Berger Paints India Ltd": "BERGEPAINT.BO",
    "Biocon Ltd": "BIOCON.NS",
    "Bosch Ltd": "BOSCHLTD.NS",
    "Britannia Industries Ltd": "BRITANNIA.BO",
    "Cholamandalam Investment and Finance Company Ltd": "CHOLAFIN.BO",
    "Cipla Ltd": "CIPLA.BO",
    "Coal India Ltd": "COALINDIA.BO",
    "Crompton Greaves Consumer Electricals Ltd": "CROMPTON.NS",
    "Dabur India Ltd": "DABUR.BO",
    "Dalmia Bharat Ltd": "DALBHARAT.NS",
    "Deepak Nitrite Ltd": "DEEPAKNTR.NS",
    "Divi's Laboratories Ltd": "DIVISLAB.BO",
    "Dr. Reddy's Laboratories Ltd": "DRREDDY.BO",
    "EID Parry (India) Ltd": "EIDPARRY.NS",
    "Eicher Motors Ltd": "EICHERMOT.BO",
    "Escorts Kubota Ltd": "ESCORTS.NS",
    "Exide Industries Ltd": "EXIDEIND.NS",
    "Federal Bank Ltd": "FEDERALBNK.NS",
    "Fortis Healthcare Ltd": "FORTIS.NS",
    "GAIL (India) Ltd": "GAIL.BO",
    "GMR Airports Infrastructure Ltd": "GMRINFRA.NS",
    "Godrej Consumer Products Ltd": "GODREJCP.BO",
    "Godrej Industries Ltd": "GODREJIND.NS",
    "Godrej Properties Ltd": "GODREJPROP.NS",
    "Grasim Industries Ltd": "GRASIM.BO",
    "Gujarat Gas Ltd": "GUJGASLTD.NS",
    "HCL Technologies Ltd": "HCLTECH.BO",
    "HDFC Bank Ltd": "HDFCBANK.BO",
    "HDFC Life Insurance Company Ltd": "HDFCLIFE.BO",
    "Havells India Ltd": "HAVELLS.BO",
    "Hero MotoCorp Ltd": "HEROMOTOCO.BO",
    "Hindalco Industries Ltd": "HINDALCO.BO",
    "Hindustan Aeronautics Ltd": "HAL.BO",
    "Hindustan Unilever Ltd": "HINDUNILVR.BO",
    "Hindustan Zinc Ltd": "HINDZINC.NS",
    "ICICI Bank Ltd": "ICICIBANK.BO",
    "ICICI Lombard General Insurance Company Ltd": "ICICIGI.BO",
    "ICICI Prudential Life Insurance Company Ltd": "ICICIPRULI.BO",
    "IDBI Bank Ltd": "IDBI.NS",
    "IDFC First Bank Ltd": "IDFCFIRSTB.NS",
    "ITC Ltd": "ITC.BO",
    "Indian Oil Corporation Ltd": "IOC.NS",
    "Indian Railway Catering and Tourism Corporation Ltd": "IRCTC.NS",
    "IndusInd Bank Ltd": "INDUSINDBK.BO",
    "Infosys Ltd": "INFY.BO",
    "InterGlobe Aviation Ltd": "INDIGO.BO",
    "JSW Steel Ltd": "JSWSTEEL.BO",
    "Jindal Steel & Power Ltd": "JINDALSTEL.BO",
    "Jubilant Foodworks Ltd": "JUBLFOOD.NS",
    "Kansai Nerolac Paints Ltd": "KANSAINER.NS",
    "Kotak Mahindra Bank Ltd": "KOTAKBANK.BO",
    "L&T Technology Services Ltd": "LTTS.BO",
    "LTIMindtree Ltd": "LTIM.BO",
    "Larsen & Toubro Ltd": "LT.BO",
    "Lupin Ltd": "LUPIN.NS",
    "MRF Ltd": "MRF.BO",
    "Mahindra & Mahindra Ltd": "M&M.BO",
    "Maruti Suzuki India Ltd": "MARUTI.BO",
    "Motherson Sumi Wiring India Ltd": "MSUMI.NS",
    "NMDC Ltd": "NMDC.NS",
    "NTPC Ltd": "NTPC.BO",
    "Nestle India Ltd": "NESTLEIND.BO",
    "Nykaa (FSN E-Commerce Ventures Ltd)": "NYKAA.NS",
    "ONGC Ltd": "ONGC.BO",
    "Oberoi Realty Ltd": "OBEROIRLTY.NS",
    "PVR Ltd": "PVRINOX.NS",
    "Page Industries Ltd": "PAGEIND.BO",
    "Paytm": "PAYTM.NS",
    "Petronet LNG Ltd": "PETRONET.BO",
    "Pidilite Industries Ltd": "PIDILITIND.BO",
    "Piramal Enterprises Ltd": "PEL.BO",
    "Power Grid Corporation of India Ltd": "POWERGRID.BO",
    "Procter & Gamble Hygiene and Health Care Ltd": "PGHH.BO",
    "RBL Bank Ltd": "RBLBANK.NS",
    "Rajesh Exports Ltd": "RAJESHEXPO.NS",
    "Reliance Industries Ltd": "RELIANCE.BO",
    "SBI Cards and Payment Services Ltd": "SBICARD.NS",
    "SBI Life Insurance Company Ltd": "SBILIFE.BO",
    "SRF Ltd": "SRF.BO",
    "Shree Cement Ltd": "SHREECEM.BO",
    "Shriram Transport Finance Company Ltd": "SRTRANSFIN.NS",
    "Siemens Ltd": "SIEMENS.BO",
    "State Bank of India": "SBIN.BO",
    "Sun Pharmaceutical Industries Ltd": "SUNPHARMA.BO",
    "Supreme Industries Ltd": "SUPREMEIND.NS",
    "TVS Motor Company Ltd": "TVSMOTOR.NS",
    "Tata Chemicals Ltd": "TATACHEM.NS",
    "Tata Communications Ltd": "TATACOMM.NS",
    "Tata Consultancy Services Ltd": "TCS.BO",
    "Tata Consumer Products Ltd": "TATACONSUM.BO",
    "Tata Elxsi Ltd": "TATAELXSI.NS",
    "Tata Investment Corporation Ltd": "TATAINVEST.NS",
    "Tata Power Company Ltd": "TATAPOWER.NS",
    "Tata Steel Ltd": "TATASTEEL.BO",
    "Tech Mahindra Ltd": "TECHM.BO",
    "Titan Company Ltd": "TITAN.BO",
    "Torrent Pharmaceuticals Ltd": "TORNTPHARM.BO",
    "UPL Ltd": "UPL.BO",
    "UltraTech Cement Ltd": "ULTRACEMCO.BO",
    "United Breweries Ltd": "UBL.BO",
    "United Spirits Ltd": "MCDOWELL-N.BO",
    "Varun Beverages Ltd": "VBL.BO",
    "Vedanta Ltd": "VEDL.BO",
    "Vodafone Idea Ltd": "IDEA.NS",
    "Voltas Ltd": "VOLTAS.NS",
    "Whirlpool of India Ltd": "WHIRLPOOL.NS",
    "Wipro Ltd": "WIPRO.BO",
    "Yes Bank Ltd": "YESBANK.NS",
    "Zee Entertainment Enterprises Ltd": "ZEEL.BO",
    "Zomato Ltd": "ZOMATO.NS",
    "Zydus Lifesciences Ltd": "ZYDUSLIFE.NS",
}
